position_order = {
    "PG": 1,
    "SG": 2,
    "SF": 3,
    "PF": 4,
    "C": 5,
}

team_endpoints = {
    "celtics": "bos/boston-celtics",
    "hawks": "atl/atlanta-hawks",
    "bucks": "mil/milwaukee-bucks",
    "bulls": "chi/chicago-bulls",
    "cavaliers": "cle/cleveland-cavaliers",
    "clippers": "lac/la-clippers",
    "grizzlies": "mem/memphis-grizzlies",
    "heat": "mia/miami-heat",
    "hornets": "cha/charlotte-hornets",
    "jazz": "uta/utah-jazz",
    "kings": "sac/sacramento-kings",
    "knicks": "nyk/new-york-knicks",
    "lakers": "lal/los-angeles-lakers",
    "magic": "orl/orlando-magic",
    "mavericks": "dal/dallas-mavericks",
    "nets": "bkn/brooklyn-nets",
    "nuggets": "den/denver-nuggets",
    "pacers": "ind/indiana-pacers",
    "pelicans": "nor/new-orleans-pelicans",
    "pistons": "det/detroit-pistons",
    "raptors": "tor/toronto-raptors",
    "rockets": "hou/houston-rockets",
    "sixers": "phi/philadelphia-76ers",
    "spurs": "sas/san-antonio-spurs",
    "suns": "phx/phoenix-suns",
    "thunder": "okc/oklahoma-city-thunder",
    "timberwolves": "min/minnesota-timberwolves",
    "warriors": "gsw/golden-state-warriors",
    "wizards": "was/washington-wizards",
}
